#!/usr/bin/env bash
#
# Contains shared scripts

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..

function taskStart() {
    echo -e "\n==> $1\n"
}

function taskEnd() {
    echo -e "\n==> Done!\n"
}

function taskProgress() {
    echo -e "\n--> $1\n"
}

function taskDebug() {
    echo -e "~~~~~~~~~~ $1"
}

function taskError() {
    echo -e "\nERR: $1\n" >&2
    exit 1
}

function aptInstall() {
    local _BIN=$1
    local _PKG=$2
    #install apt package if its main command binary not already installed
    if ! builtin type -p $_BIN &>/dev/null; then
        taskProgress "installing ${_PKG}. this may take a couple of minutes"
        sudo apt-get -qq -y update
        sudo apt-get -qq -y install $_PKG
    fi
}


function fixUbuntuRepoKey(){
    sudo echo "Acquire::http::Proxy \"http://str-www-proxy2.homedepot.com:8080\";" | sudo tee -a /etc/apt/apt.conf
}
